### ISSUE TITLE
The label of Plot Matrix is not right, why?

### ISSUE THREAD

**Issue by xiasijian** [bioconductor-source/HiContacts#1]
![image](https://github.com/user-attachments/assets/3baedf4c-4392-4f9b-a5ec-22c947c2fc54)

This is your example
![image](https://github.com/user-attachments/assets/9a84447f-7776-4dbf-a9c0-bef32ab1639e)

**Comment by lshep** [comment]
This is not the right location to ask questions. This is a testing repository. Please ask questions on support.bioconductor.org or check the Bioconductor package landing page for information on maintainer
